In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as plt


In [2]:
df=sns.load_dataset('iris')

In [3]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [4]:
np.mean(df['petal_length'])

np.float64(3.7580000000000005)

In [6]:
import numpy as np
numbers=[1,2,3,4]
numbers_array=np.array(numbers)
print(numbers_array)
multiple_numbers=np.array([[1,3,5],[1,5,8]])
print(multiple_numbers)

[1 2 3 4]
[[1 3 5]
 [1 5 8]]


In [7]:
# array range function
# range expects an integer
numbers=np.arange(1,50,.5)
print(numbers)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5
 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5
 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5
 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5
 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5]


In [9]:
# zeros
zeroes=np.zeros((10,10),dtype=bool)
print(zeroes)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


In [10]:
# ones
ones=np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
# empty arry
empty=np.empty((4,4))
print(empty)

[[6.22544147e-312 4.15015143e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.16095484e-028 7.52736900e+252 4.11710005e+223]
 [3.75586847e+233 3.10573437e-115 3.77075632e+233 3.65091999e+233]
 [1.46899930e+179 9.08367237e+223 1.16466228e-028 1.03772355e-314]]


In [12]:
# random
np.random.rand()

0.30419331659936266

In [14]:
# random
np.random.rand(3,4)

array([[0.28270419, 0.07164559, 0.13313089, 0.9468982 ],
       [0.04312034, 0.25889998, 0.88956123, 0.98277048],
       [0.64583756, 0.42464868, 0.02835294, 0.89141916]])

In [ ]:
%timeit
