In [2]:
# 2d array
import numpy as np
arry=np.array([[1,3,4],[5,6,8]])
print(arry)
print(np.ndim(arry))
print(type(arry))

[[1 3 4]
 [5 6 8]]
2
<class 'numpy.ndarray'>


In [9]:
# 3d array
array_3d=np.array([[[1,3,5],[7,7,8],[1,1,1]]])
print(array_3d)
print(np.ndim(array_3d))
print(type(array_3d))

[[[1 3 5]
  [7 7 8]
  [1 1 1]]]
3
<class 'numpy.ndarray'>


In [10]:
# multidiemensional array
array_mul_d=np.array([[[[1,4,5],[1,7,9],[8,9,10],[1,1,5]]]])
print(array_mul_d)
print(np.ndim(array_mul_d))
print(type(array_mul_d))

[[[[ 1  4  5]
   [ 1  7  9]
   [ 8  9 10]
   [ 1  1  5]]]]
4
<class 'numpy.ndarray'>


In [16]:
# dynamic data types of array
array=np.array([[[1,3,4],[1,3,4]]],dtype=float)
array_1=np.array([[[1,0,-1],[1,0,-8]]],dtype=bool)
array_2=np.array([[1,9,10],[1,4,6]],dtype=complex)
print(array_1)
print(array)
print(array_2)
print(np.ndim(array_2))

[[[ True False  True]
  [ True False  True]]]
[[[1. 3. 4.]
  [1. 3. 4.]]]
[[ 1.+0.j  9.+0.j 10.+0.j]
 [ 1.+0.j  4.+0.j  6.+0.j]]
2


In [22]:
# array range function
array=np.arange(1,51,2)
print(array)
# reshape
array_1=np.arange(1,41).reshape(8,5)
print(array_1)
print(np.ndim(array_1))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]
2


In [26]:
# random
np.random.random((1,10))

array([[0.51017846, 0.45893502, 0.16594098, 0.56875371, 0.67753926,
        0.02745007, 0.46159796, 0.3060489 , 0.55889976, 0.07973581]])

In [30]:
# linspace
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [32]:
# identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [33]:
a=np.arange(1,15)
b=np.arange(12,dtype=float).reshape(3,4)
c=np.arange(8).reshape(2,2,2)
print(a)
print(b)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [36]:
# scaller operations
a=np.arange(1,13).reshape(4,3)
print(a)
print('='*15)
print(a*3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]
 [30 33 36]]


In [39]:
a=np.array([[1,5,7],[5,8,9]])
b=np.array([[4,8,16],[12,16,18]])

print(a)
print(b)
print(np.ndim(a))
print('='*20)

dot=np.dot(a,b)
print(dot)

[[1 5 7]
 [5 8 9]]
[[ 4  8 16]
 [12 16 18]]
2


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)