In [1]:
import numpy as np

In [2]:
# list indexing
x=list(range(1,11))
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
x[0]
x[1:10:3]

[2, 5, 8]

In [4]:
# array indexing
y=np.array(list(range(1,11)))
y[0:4]
y[0:8:3]

array([1, 4, 7])

In [5]:
# list of lists
x=[list(range(1,3)) for _ in range(3)]

In [18]:
x=np.array([[[1,3,5],[1,7,9],[1,9,0]]])
x[0,1]

array([1, 7, 9])

In [27]:
# fancy indexing
import seaborn as sns
df=sns.load_dataset('iris')
df.head()
sepal_length=df['sepal_width']<3
sepal_length
df[sepal_length]


,sepal_length,sepal_width,petal_length,petal_width,species
8,4.4,2.9,1.4,0.2,setosa
41,4.5,2.3,1.3,0.3,setosa
53,5.5,2.3,4.0,1.3,versicolor
54,6.5,2.8,4.6,1.5,versicolor
55,5.7,2.8,4.5,1.3,versicolor
57,4.9,2.4,3.3,1.0,versicolor
58,6.6,2.9,4.6,1.3,versicolor
59,5.2,2.7,3.9,1.4,versicolor
60,5.0,2.0,3.5,1.0,versicolor
62,6.0,2.2,4.0,1.0,versicolor


In [ ]:
import numpy as np
array=np.arrage(1,16).reshape(5,3)
array

In [8]:
x=np.arange(1,101).reshape(10,10)
print(x)
print(np.ndim(x))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
2


In [ ]:
# indexing
x[0:5,0:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [ ]:
#indexing
x[:,:4]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64],
       [71, 72, 73, 74],
       [81, 82, 83, 84],
       [91, 92, 93, 94]])

In [12]:
x=np.arange(1,13).reshape(2,3,2)
print(x)
print(np.ndim(x))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [19]:
# let say I want to fetch 12
x[1,2,1]

np.int64(12)

In [21]:
# 
m=np.arange(1,21).reshape(5,2,2)
m

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [22]:
# fetch 17
m[4,0,0]

np.int64(17)

In [27]:
x=np.arange(1,1001).reshape(100,2,5)
x

array([[[   1,    2,    3,    4,    5],
        [   6,    7,    8,    9,   10]],

       [[  11,   12,   13,   14,   15],
        [  16,   17,   18,   19,   20]],

       [[  21,   22,   23,   24,   25],
        [  26,   27,   28,   29,   30]],

       [[  31,   32,   33,   34,   35],
        [  36,   37,   38,   39,   40]],

       [[  41,   42,   43,   44,   45],
        [  46,   47,   48,   49,   50]],

       [[  51,   52,   53,   54,   55],
        [  56,   57,   58,   59,   60]],

       [[  61,   62,   63,   64,   65],
        [  66,   67,   68,   69,   70]],

       [[  71,   72,   73,   74,   75],
        [  76,   77,   78,   79,   80]],

       [[  81,   82,   83,   84,   85],
        [  86,   87,   88,   89,   90]],

       [[  91,   92,   93,   94,   95],
        [  96,   97,   98,   99,  100]],

       [[ 101,  102,  103,  104,  105],
        [ 106,  107,  108,  109,  110]],

       [[ 111,  112,  113,  114,  115],
        [ 116,  117,  118,  119,  120]],

       [[ 121,  

In [29]:
# fetching 65
x[6,0,-1]

np.int64(65)

In [30]:
# fetching 1000
x[-1,-1,-1]

np.int64(1000)