In [1]:
import numpy as np

In [6]:
x=list(range(0,4))
y=x
x
x[0]='a'


In [7]:
y

['a', 1, 2, 3]

In [12]:
x=np.arange(1,4)
x[0]=7
y=x

In [13]:
x

array([7, 2, 3])

In [14]:
y

array([7, 2, 3])

In [15]:
print(id(x))
print(id(y))

2058898542480
2058898542480


In [17]:
x=np.arange(1,101)
y=x[1:10]
print(id(x))
print(id(y))

2058898063056
2058903193136


In [ ]:
x=np.arange(1,101).reshape(10,10)
print(x)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [24]:
y=x.reshape(5,20)
np.may_share_memory(x,y)

True

In [22]:
y=x[1:10,1:3]
y

array([[12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])