In [2]:
import numpy as np
second=np.arange(11,20)
first=np.arange(1,10)
first+second

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [5]:
x=np.arange(1,11)
y=np.arange(1,11).reshape(5,2)
print(x)
print(y)
print(x+y)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


ValueError: operands could not be broadcast together with shapes (10,) (5,2) 